# Generated by Django 5.0 on 2023-12-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
