# Generated by Django 5.0 on 2023-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customer_customer_id_customer_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
