# Generated by Django 5.0 on 2023-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customer_id_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
