# Generated by Django 5.0 on 2023-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
